### PR TITLE
Handle multiple packets

### PR DESCRIPTION
**Pull request by brunchboy**
This pull request is a first step towards fixing issue #1 but is not yet complete. These changes should properly handle the situation where CoreMIDI is sending multiple MIDI packets at one time, as documented [here](https://developer.apple.com/library/ios/documentation/CoreMidi/Reference/MIDIServices_Reference/#//apple_ref/c/tdef/MIDIPacketList) (although note that in their code sample, the logic of the condition expression in their `for` loop is reversed, and should use `<` rather than `>`).

Unfortunately, that is not the only kind of compression that CoreMIDI does. It is also sending multiple MIDI messages in each packet, so the Java code in `CoreMidiSource.messageCallback` is going to need to expand into a loop which processes messages until the sum of the lengths of messages processed reaches the length of the packet. I have not yet figured out how to build the JAR, so I may be stuck for now.

### CODE REVIEW

**Comment by brunchboy** [comment]
All right, I have been able to get this working. Now, even when CoreMIDI sends multiple MIDI messages in a packet, they all get delivered to Java clients properly.

I had to make a pretty substantial change to the way SYSEX messages were handled, but I think that in doing so I fixed another bug that would have manifested itself upon the first receipt of a multi-packet SYSEX message: The message handling code was only treating the second packet as a SYSEX continuation if the first byte did not happen to be a recognizable MIDI message. Now if it is expecting part of a SYSEX message, it handles all bytes as that until the F7.

I am sorry that the whole Java source file got reformatted so it will be harder to see my specific changes, but I could not get my IDE to cope with the way it was formatted previously. Perhaps if you reformat it in yours, it will be easier to diff then.

I hope these changes make sense and are useful! It has fixed the problem I was having with Traktor.

**Comment by DerekCook** [comment]
All makes sense. I will do a merge of these commits in the next update

**Comment by brunchboy** [comment]
Great! Please be sure to carefully test reception of SYSEX messages, because I don’t have any equipment to do that with, and I would hate to have broken that on you.

**Comment by DerekCook** [comment]
No worries. I will check the changes out. Due to changes I have already made, I am having to merge these changes manually. So once I have done that, I will close this pull request and make a fresh commit with the changes in.

**Comment by DerekCook** [comment]
The suggested changes have been manually merged with the Master branch, so I will close this pull request

**Comment by brunchboy** [comment]
Thanks! Sorry about the hassle of dealing with merge conflicts.

**Pull request closed without merging**
